[build]
builder = "NIXPACKS"

[build.env]
NIXPACKS_NODE_VERSION = "18"
NIXPACKS_PKGS = "nodejs-18_x"

[build.buildCommand]
command = "npm install && npm run build"

[deploy]
startCommand = "php artisan serve --host=0.0.0.0 --port=$PORT"

[deploy.env]
APP_ENV = "production"
